services:
  proxy:
    image: nginx:alpine
    env_file: .env
    environment:
      - NGINX_ENTRYPOINT_LOCAL_RESOLVERS: 1
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
